services:
  frontend:
    restart: always
    build: ./frontend
    ports:
      - '3000:3000'
    volumes:
      - /app/node_modules
      - ./frontend:/app
    environment:
      - WATCHPACK_POLLING=tru
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - ./api/.env.local

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - '6379:6379'
  api:
    build: ./api
    command: daphne -b 0.0.0.0 -p 8000 myproject.asgi:application
    working_dir: /code/myproject
    env_file:
      - ./api/.env.local
    volumes:
      - ./api:/code/
      - ./api/media:/code/media

    ports:
      - '8000:8000'
    depends_on:
      - db
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    env_file:
      - ./api/.env.local
    ports:
      - '5050:80'
    depends_on:
      - db
    volumes:
      - ./data/pgadmin:/var/lib/pgadmin
