# Generated by Django 5.1.7 on 2025-03-31 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_image_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='author_url',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='unsplash_id',
            field=models.CharField(blank=True, null=True),
        ),
    ]
